multipleAnswers = false

[[settings]]
text = "Min value"
type = "int"
default = 0

[[settings]]
text = "Max value"
type = "int"
default = 30

[[settings]]
text = "Threshold"
type = "float"
default = 0.5